/*USE TanksofWWII;

ALTER TABLE Tank WITH CHECK
ADD CONSTRAINT FK_StatID FOREIGN KEY(StatID) REFERENCES Stats(StatID)
ON UPDATE CASCADE

ALTER TABLE Tank WITH CHECK
ADD CONSTRAINT FK_MfgrID FOREIGN KEY(MfgrID) REFERENCES Mfgr(MfgrID)
ON UPDATE CASCADE

ALTER TABLE TanksInBattle WITH CHECK
ADD CONSTRAINT FK_TankID FOREIGN KEY(TankID) REFERENCES Tank(TankID)
ON UPDATE CASCADE;

ALTER TABLE TanksInBattle WITH CHECK
ADD CONSTRAINT FK_BattleID FOREIGN KEY(BattleID) REFERENCES Battles(BattleID)
ON UPDATE CASCADE;

ALTER TABLE Mfgr WITH CHECK
ADD CONSTRAINT FK_CountryID FOREIGN KEY(CountryID) REFERENCES Country(CountryID)
ON UPDATE CASCADE;

ALTER TABLE CountrysInBattle WITH CHECK
ADD CONSTRAINT FK_BattleID2 FOREIGN KEY(BattleID) REFERENCES Battles(BattleID)
ON UPDATE CASCADE;

ALTER TABLE CountrysInBattle WITH CHECK
ADD CONSTRAINT FK_CountryID2 FOREIGN KEY(CountryID) REFERENCES Country(CountryID)
ON UPDATE CASCADE;*/
